### ISSUE TITLE
arCNiso 模块化

### ISSUE THREAD

**Issue by clsty** [clsty/arCNiso#27]
现在已实现arCNiso补丁化，这为下一步实现模块化奠定了基础。

进而，由于模块化获得灵活性，就有更容易同时支持更多的架构(risc-v、arm等）（在没有模块化之前，多架构支持的最大问题在于，适合 x86 的包 risc-v 未必有）。

**Comment by clsty** [comment]
同时，模块化之后也使本项目的结构更加清晰，便于他人参与贡献或自行定制。
但应当注意，最好能找到方法来避免模块间的冲突（比如打成 pacman 的包，这样若有文件冲突，在安装时就会提示了）。

**Comment by clsty** [comment]
多语言可以考虑这个：
https://www.linuxjournal.com/content/internationalizing-those-bash-scripts

**Comment by clsty** [comment]
一种实现思路：用 yaml 指定模块的配置，在主脚本中使用 yq 解析 yaml。

设想中的 yaml 形态：
```yaml
# config.yaml
version: "1.0"
modules:
  - name: "locale"
    enabled: true
    flavor: zh-CN
  - name: "browser"
    enabled: true
    flavor: firefox
... 
```

目录结构：
- `config.yaml`
- `modules`
  - `locale`
    - `setup.sh`
    - 其它相关文件
  - `browser`
    - `setup.sh`
    - 其它相关文件
 
当 `enabled` 为 `true` 时，就在主脚本中 `source` 对应 `module` 目录下的 `setup.sh`。
